apiVersion: v1
kind: PersistentVolume
metadata:
  name: webhook-pv
  labels:
    type: local
spec:
  storageClassName: webhook
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webhook-pvc
  namespace: webhookserver-ns
  labels: 
    app: webhookserver
spec:
  storageClassName: webhook
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi