apiVersion: v1
kind: Pod
metadata:
  namespace: admissionwebhook-ns
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sleep", "1d"]
    imagePullPolicy: IfNotPresent
    resources: 
      limits:
        memory: 512Mi
        cpu: "1"
