apiVersion: v1
kind: Pod
metadata:
  namespace: admissionwebhook-ns
  name: node-app
  labels:
    app: node-app
spec:
  securityContext:
    runAsUser: 3000
  containers:
  - name: node-app
    image: yulypso/node-app:v0.0.1
    imagePullPolicy: IfNotPresent
    resources: 
      limits:
        memory: 512Mi
        cpu: "1"
