apiVersion: v1
kind: Pod
metadata:
  namespace: admissionwebhook-ns
  name: node-app
  labels:
    a4c_nodeid: node-app
  annotations:
    artemis.site: prod
spec:
  volumes:
  - name: test-volume
    hostPath:
      path: /data
      type: Directory
  securityContext:
    runAsUser: 3000
    runAsNonRoot: false
  initContainers:
  - name: init0
    image: yulypso/node-app:v0.0.1
  - name: init1
    image: yulypso/node-app:v0.0.1
  - name: init2
    image: yulypso/node-app:v0.0.1
  containers:
  - name: node-app0
    image: yulypso/node-app:v0.0.1
    imagePullPolicy: IfNotPresent
    resources: 
      limits:
        memory: 512Mi
        cpu: "1"
    securityContext:
      allowPrivilegeEscalation: true    
  - name: node-app1
    image: yulypso/node-app:v0.0.1
    imagePullPolicy: IfNotPresent
    resources: 
      limits:
        memory: 512Mi
        cpu: "1"
    securityContext:
      allowPrivilegeEscalation: true    
  - name: node-app2
    image: yulypso/node-app:v0.0.1
    imagePullPolicy: IfNotPresent
    resources: 
      limits:
        memory: 512Mi
        cpu: "1"
    securityContext:
      allowPrivilegeEscalation: true    
  